# Conda environment for "No Evidence for Epistemic Entropy Collapse in Small Open Language Models"
#
# Create with: conda env create -f environment.yml
# Activate with: conda activate eec-null

name: eec-null
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - scipy=1.11.1
  - scikit-learn=1.3.0
  - pyarrow=12.0.1
  - tqdm=4.65.0
  - click=8.1.6
  - pip
  - pip:
    - ruff==0.0.285
    - black==23.7.0
