name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install ruff==0.0.285 black==23.7.0

      - name: Run lint check
        run: bash scripts/lint_check.sh

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Verify environment
        run: bash scripts/verify_environment.sh

      - name: Run smoke test
        run: bash scripts/run_smoke.sh
        timeout-minutes: 10

      - name: Upload smoke test figures
        uses: actions/upload-artifact@v3
        with:
          name: smoke-test-figures
          path: runs/affordable/figures/*_smoke.png
